name: 'Manual Dependabot'
on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Target branch for Dependabot'
        required: true
  push:
    paths:
        - "pyproject.toml"
        - "requirements.txt"
        - ".github/**"

jobs:
  run-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Dependabot
        uses: docker://ghcr.io/dependabot/dependabot-core
        env:
          TARGET_BRANCH: ${{ github.event_name == 'push' && github.ref_name || github.event.inputs.target-branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          entrypoint: bundle
          args: exec dependabot update --config-file .github/dependabot.yml --target-branch ${{ env.TARGET_BRANCH }}
