name: 'Manual Dependabot'
on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Target branch for Dependabot'
        required: true
  push:
    paths:
        - "pyproject.toml"
        - "requirements.txt"
        - ".github/**"


jobs:
  run-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependabot
        run: pip install dependabot-core

      - name: Run Dependabot
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            target_branch=${GITHUB_REF#refs/heads/}
          else
            target_branch=${{ github.event.inputs.target-branch }}
          fi
          dependabot update --target-branch $target_branch