name: 'Manual Dependabot'
on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Target branch for Dependabot'
        required: true
  push:
    paths:
        - "pyproject.toml"
        - "requirements.txt"
        - ".github/**"

jobs:
  run-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Install Dependabot CLI
        run: go install github.com/dependabot/cli/cmd/dependabot@latest
      
      - name: Run Dependabot
        env:
          TARGET_BRANCH: ${{ github.event_name == 'push' && github.ref_name || github.event.inputs.target-branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dependabot update pip ${{ github.repository }} \
            --branch ${{ env.TARGET_BRANCH }} \
            --updater-image dependabot/dependabot-core:latest
